const http = require('http'), fs = require('fs'), path = require('path');
const root = __dirname;
const port = process.env.PORT || 8080;
const donationsDir = process.env.DONATIONS_DIR || path.join(root, 'donations');
const mime = { '.js': 'application/javascript', '.html': 'text/html', '.mp3': 'audio/mpeg', '.webm': 'audio/webm', '.json': 'application/json', '.yaml': 'text/yaml', '.css': 'text/css', '.svg': 'image/svg+xml', '.png': 'image/png', '.ico': 'image/x-icon', '.zip': 'application/zip' };

function ensureDir(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

http.createServer((req, res) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') { res.writeHead(204); res.end(); return; }

  /* POST /api/donate — accept audio contribution */
  if (req.method === 'POST' && req.url === '/api/donate') {
    var body = [];
    req.on('data', function(c) { body.push(c); });
    req.on('end', function() {
      try {
        var data = JSON.parse(Buffer.concat(body).toString());
        var id = data.id, audioBase64 = data.audioBase64, yaml = data.yaml, ext = data.ext;
        var audioDir = path.join(donationsDir, 'audio');
        ensureDir(audioDir);
        var audioBuffer = Buffer.from(audioBase64, 'base64');
        fs.writeFileSync(path.join(audioDir, id + '.' + ext), audioBuffer);
        var yamlPath = path.join(donationsDir, 'contributions.yaml');
        var yamlContent = '';
        if (fs.existsSync(yamlPath)) {
          yamlContent = fs.readFileSync(yamlPath, 'utf8').trimEnd() + '\n';
        } else {
          yamlContent = '# Contributions manifest\n# Generated by Voice Contributor\n# License: CC-BY-4.0\ncontributions:\n';
        }
        yamlContent += yaml + '\n';
        fs.writeFileSync(yamlPath, yamlContent);
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ ok: true, id: id }));
      } catch (e) {
        res.writeHead(400, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ ok: false, error: e.message }));
      }
    });
    return;
  }

  /* GET /api/donations/yaml — return contributions.yaml content */
  if (req.url === '/api/donations/yaml') {
    var yamlPath = path.join(donationsDir, 'contributions.yaml');
    if (!fs.existsSync(yamlPath)) { res.writeHead(404); res.end('No contributions yet'); return; }
    var yaml = fs.readFileSync(yamlPath, 'utf8');
    res.writeHead(200, { 'Content-Type': 'text/yaml;charset=utf-8' });
    res.end(yaml);
    return;
  }

  /* GET /api/donations/audio/* — serve audio files from volume */
  var audioMatch = req.url.match(/^\/api\/donations\/audio\/(.+)$/);
  if (audioMatch) {
    var audioFile = path.join(donationsDir, 'audio', audioMatch[1]);
    if (!fs.existsSync(audioFile)) { res.writeHead(404); res.end('File not found'); return; }
    var ext = path.extname(audioFile);
    res.writeHead(200, { 'Content-Type': mime[ext] || 'audio/webm' });
    fs.createReadStream(audioFile).pipe(res);
    return;
  }

  /* GET /api/donations — list all files on volume */
  if (req.url === '/api/donations') {
    var donDir = donationsDir;
    if (!fs.existsSync(donDir)) { res.writeHead(404); res.end('No donations yet'); return; }
    /* Simple directory listing as JSON */
    var files = [];
    function walk(dir, prefix) {
      if (!fs.existsSync(dir)) return;
      var entries = fs.readdirSync(dir, { withFileTypes: true });
      entries.forEach(function(e) {
        if (e.name === '.gitkeep') return;
        var rel = prefix ? prefix + '/' + e.name : e.name;
        if (e.isDirectory()) walk(path.join(dir, e.name), rel);
        else files.push(rel);
      });
    }
    walk(donDir, '');
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ files: files }));
    return;
  }

  /* Redirects */
  if (req.url === '/') { res.writeHead(302, { Location: '/apps/river-world/' }); res.end(); return; }
  if (req.url === '/apps/river-world') { res.writeHead(302, { Location: '/apps/river-world/' }); res.end(); return; }
  if (req.url === '/apps/river-world/') { req.url = '/apps/river-world/index.html'; }
  if (req.url === '/apps/voice-contrib') { res.writeHead(302, { Location: '/apps/voice-contrib/' }); res.end(); return; }
  if (req.url === '/apps/voice-contrib/') { req.url = '/apps/voice-contrib/index.html'; }

  /* Static files */
  var url = req.url.split('?')[0];
  var f = path.join(root, url.replace(/\\/g, '/').replace(/^\/+/, ''));
  try {
    var d = fs.readFileSync(f);
    var ext = path.extname(f);
    res.writeHead(200, {'Content-Type': mime[ext] || 'application/octet-stream'});
    res.end(d);
  } catch(e) {
    res.writeHead(404);
    res.end('404: ' + url);
  }
}).listen(port, function() {
  console.log('http://localhost:' + port + '  (or http://localhost:' + port + '/apps/voice-contrib/)');
});
