"""Regenerate JS bundles and copy audio files to app/docs dirs."""
import sys, shutil, yaml, re
from pathlib import Path

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT / "core"))

from languages.surface_form import SurfaceFormRegistry
from languages.voice_package import VoicePackageRegistry

# --- surface_forms.js ---
sf_reg = SurfaceFormRegistry.from_yaml(
    ROOT / "experiences" / "river_world" / "surface_forms.yaml"
)
sf_js = sf_reg.to_js_bundle()

for dest in [ROOT / "apps" / "river-world", ROOT / "docs"]:
    (dest / "surface_forms.js").write_text(sf_js, encoding="utf-8")
    print(f"Wrote surface_forms.js to {dest}")

# --- voice_packages.js ---
vp_reg = VoicePackageRegistry.from_directory(
    ROOT / "experiences" / "river_world" / "voices"
)
vp_js = vp_reg.to_js_bundle()

for dest in [ROOT / "apps" / "river-world", ROOT / "docs"]:
    (dest / "voice_packages.js").write_text(vp_js, encoding="utf-8")
    print(f"Wrote voice_packages.js to {dest}")

# --- maori-phrases.js — sentence-level recording registry (initially empty) ---
# Populated from RIVER YAML files so structure is ready for when recordings are added
RIVER_DIR = ROOT / "experiences" / "river_world"
mi_phrases = []
for yf in sorted(RIVER_DIR.glob("RIVER_*.yaml")):
    with open(yf, encoding="utf-8") as f:
        data = yaml.safe_load(f)
    exp_id = data.get("experience_id", yf.stem)
    mi_content = data.get("content", {}).get("mi", "")
    # Split into individual sentences
    sentences = [s.strip() for s in re.split(r'(?<=[.!?])\s+', mi_content) if s.strip()]
    for idx, sentence in enumerate(sentences):
        phrase_id = f"{exp_id}_S{idx+1:02d}"
        mi_phrases.append({
            "id": phrase_id,
            "lang": "mi",
            "text": sentence,
            "intent": exp_id,
            "situation": f"Sentence {idx+1} of {exp_id}",
            "audio_refs": [],  # No recordings yet; populate when acquired
        })
    # Also add a full-passage entry (no audio_refs yet)
    mi_phrases.append({
        "id": exp_id,
        "lang": "mi",
        "text": mi_content.strip(),
        "intent": exp_id,
        "type": "passage",
        "situation": f"Full passage recording for {exp_id}",
        "audio_refs": [],
    })

# Generate JS bundle using json.dumps (valid JS object literal syntax)
import json
mi_json = json.dumps(mi_phrases, ensure_ascii=False, indent=2)
lines = [
    "/**",
    " * Māori Phrase Registry — sentence & passage-level recordings (extensible).",
    " * Auto-generated by rebuild_js.py from RIVER YAML files.",
    " * Add audio_refs to entries when sentence or passage recordings are acquired.",
    " * The runtime automatically prefers these over word-by-word composition.",
    " */",
    "var MI_PHRASES = " + mi_json + ";",
    "",
    "/**",
    " * Look up Māori phrase/sentence recordings by intent and optional type.",
    " * @param {string} intent — passage ID like 'RIVER_002'",
    " * @param {string} [type] — 'passage' for full passage, 'sentence' for individual",
    " * @returns {Array} matching phrase entries",
    " */",
    "function lookupMiPhrases(intent, type) {",
    "  if (!intent || typeof MI_PHRASES === 'undefined') return [];",
    "  return MI_PHRASES.filter(function(p) {",
    "    if (p.intent !== intent) return false;",
    "    if (type && p.type !== type) return false;",
    "    return true;",
    "  });",
    "}",
]

lines.insert(1, " *")
lines.insert(1, " * Auto-generated — do not edit directly. Edit the RIVER YAML files and rebuild.")

for dest in [ROOT / "apps" / "river-world", ROOT / "docs"]:
    (dest / "maori-phrases.js").write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote maori-phrases.js to {dest}")

# Also write to packages/language-data/ for voice-contrib tools
pkg_dir = ROOT / "docs" / "packages" / "language-data"
(pkg_dir / "maori-phrases.js").write_text("\n".join(lines), encoding="utf-8")
print(f"Wrote maori-phrases.js to {pkg_dir}")

# --- Copy audio files ---
src_voices = ROOT / "experiences" / "river_world" / "voices"
for dest in [ROOT / "apps" / "river-world" / "voices", ROOT / "docs" / "voices"]:
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(src_voices, dest)
    print(f"Copied audio files to {dest}")

print("Done")
