var SURFACE_FORMS = {
  SF_EN_THING_001: {"id": "SF_EN_THING_001", "entity_id": "THING_001", "lang": "en", "text": "water", "pronunciation": {"ipa": "/ˈwɔːtər/", "syllables": ["waw", "ter"], "stress": 1}},
  SF_MI_THING_001: {"id": "SF_MI_THING_001", "entity_id": "THING_001", "lang": "mi", "text": "wai", "pronunciation": {"syllables": ["wai"], "audio_refs": [{"ref": "wai.mp3", "package": "mi_teaka_v1", "speaker": "Te Aka Māori Dictionary", "dialect": "Standard", "speed": "normal", "quality": "field", "source_url": "https://maoridictionary.co.nz/word/9019", "retrieved": "2026-07-20", "source_license": "Copyright John C Moorfield / Te Aka Māori Dictionary — educational use"}]}},
  SF_AF_THING_001: {"id": "SF_AF_THING_001", "entity_id": "THING_001", "lang": "af", "text": "water", "pronunciation": {"ipa": "/ˈvɑːtər/", "syllables": ["va", "ter"], "stress": 1}},
  SF_EN_PLACE_005: {"id": "SF_EN_PLACE_005", "entity_id": "PLACE_005", "lang": "en", "text": "river", "pronunciation": {"ipa": "/ˈrɪvər/", "syllables": ["ri", "ver"], "stress": 1}},
  SF_MI_PLACE_005: {"id": "SF_MI_PLACE_005", "entity_id": "PLACE_005", "lang": "mi", "text": "awa", "pronunciation": {"syllables": ["a", "wa"], "audio_refs": [{"ref": "awa.mp3", "package": "mi_teaka_v1", "speaker": "Te Aka Māori Dictionary", "dialect": "Standard", "speed": "normal", "quality": "field", "source_url": "https://maoridictionary.co.nz/word/563", "retrieved": "2026-07-20", "source_license": "Copyright John C Moorfield / Te Aka Māori Dictionary — educational use"}]}},
  SF_AF_PLACE_005: {"id": "SF_AF_PLACE_005", "entity_id": "PLACE_005", "lang": "af", "text": "rivier", "pronunciation": {"ipa": "/rəˈfiːr/", "syllables": ["re", "fier"], "stress": 2}},
  SF_EN_STATE_001: {"id": "SF_EN_STATE_001", "entity_id": "STATE_001", "lang": "en", "text": "thirsty", "pronunciation": {"ipa": "/ˈθɜːrsti/", "syllables": ["thur", "sty"], "stress": 1}},
  SF_MI_STATE_001: {"id": "SF_MI_STATE_001", "entity_id": "STATE_001", "lang": "mi", "text": "matewai", "pronunciation": {"syllables": ["ma", "te", "wai"], "audio_refs": [{"ref": "matewai.mp3", "package": "mi_teaka_v1", "speaker": "Te Aka Māori Dictionary", "dialect": "Standard", "speed": "normal", "quality": "field", "source_url": "https://maoridictionary.co.nz/word/3885", "retrieved": "2026-07-20", "source_license": "Copyright John C Moorfield / Te Aka Māori Dictionary — educational use"}]}},
  SF_AF_STATE_001: {"id": "SF_AF_STATE_001", "entity_id": "STATE_001", "lang": "af", "text": "dors", "pronunciation": {"ipa": "/dɔrs/", "syllables": ["dors"]}},
  SF_EN_STATE_002: {"id": "SF_EN_STATE_002", "entity_id": "STATE_002", "lang": "en", "text": "hydrated", "pronunciation": {"ipa": "/ˈhaɪdreɪtɪd/", "syllables": ["hy", "dray", "tid"], "stress": 1}},
  SF_MI_STATE_002: {"id": "SF_MI_STATE_002", "entity_id": "STATE_002", "lang": "mi", "text": "kore matewai", "pronunciation": {"syllables": ["ko", "re", "ma", "te", "wai"]}},
  SF_AF_STATE_002: {"id": "SF_AF_STATE_002", "entity_id": "STATE_002", "lang": "af", "text": "nie dors nie", "pronunciation": {"ipa": "/ni dɔrs ni/", "syllables": ["nie", "dors", "nie"], "stress": 2}},
  SF_EN_ACTION_001: {"id": "SF_EN_ACTION_001", "entity_id": "ACTION_001", "lang": "en", "text": "drink", "pronunciation": {"ipa": "/drɪŋk/", "syllables": ["drink"]}},
  SF_MI_ACTION_001: {"id": "SF_MI_ACTION_001", "entity_id": "ACTION_001", "lang": "mi", "text": "inu", "pronunciation": {"syllables": ["i", "nu"], "audio_refs": [{"ref": "inu.mp3", "package": "mi_teaka_v1", "speaker": "Te Aka Māori Dictionary", "dialect": "Standard", "speed": "normal", "quality": "field", "source_url": "https://maoridictionary.co.nz/word/1754", "retrieved": "2026-07-20", "source_license": "Copyright John C Moorfield / Te Aka Māori Dictionary — educational use"}]}},
  SF_AF_ACTION_001: {"id": "SF_AF_ACTION_001", "entity_id": "ACTION_001", "lang": "af", "text": "drink", "pronunciation": {"ipa": "/drəŋk/", "syllables": ["drink"]}},
  SF_EN_ACTION_002: {"id": "SF_EN_ACTION_002", "entity_id": "ACTION_002", "lang": "en", "text": "walk", "pronunciation": {"ipa": "/wɔːk/", "syllables": ["walk"]}},
  SF_MI_ACTION_002: {"id": "SF_MI_ACTION_002", "entity_id": "ACTION_002", "lang": "mi", "text": "hīkoi", "pronunciation": {"syllables": ["hī", "koi"], "stress": 1, "audio_refs": [{"ref": "hīkoi.mp3", "package": "mi_teaka_v1", "speaker": "Te Aka Māori Dictionary", "dialect": "Standard", "speed": "normal", "quality": "field", "source_url": "https://maoridictionary.co.nz/word/1173", "retrieved": "2026-07-20", "source_license": "Copyright John C Moorfield / Te Aka Māori Dictionary — educational use"}]}},
  SF_AF_ACTION_002: {"id": "SF_AF_ACTION_002", "entity_id": "ACTION_002", "lang": "af", "text": "loop", "pronunciation": {"ipa": "/lʊəp/", "syllables": ["loop"]}},
  SF_EN_PERSON_003: {"id": "SF_EN_PERSON_003", "entity_id": "PERSON_003", "lang": "en", "text": "child", "pronunciation": {"ipa": "/tʃaɪld/", "syllables": ["child"]}},
  SF_MI_PERSON_003: {"id": "SF_MI_PERSON_003", "entity_id": "PERSON_003", "lang": "mi", "text": "tamaiti", "pronunciation": {"syllables": ["ta", "ma", "i", "ti"], "audio_refs": [{"ref": "tamaiti.mp3", "package": "mi_teaka_v1", "speaker": "Te Aka Māori Dictionary", "dialect": "Standard", "speed": "normal", "quality": "field", "source_url": "https://maoridictionary.co.nz/word/7326", "retrieved": "2026-07-20", "source_license": "Copyright John C Moorfield / Te Aka Māori Dictionary — educational use"}]}},
  SF_AF_PERSON_003: {"id": "SF_AF_PERSON_003", "entity_id": "PERSON_003", "lang": "af", "text": "kind", "pronunciation": {"ipa": "/kənt/", "syllables": ["kind"]}},
  SF_EN_PERSON_010: {"id": "SF_EN_PERSON_010", "entity_id": "PERSON_010", "lang": "en", "text": "mother", "pronunciation": {"ipa": "/ˈmʌðər/", "syllables": ["moth", "er"], "stress": 1}},
  SF_MI_PERSON_010: {"id": "SF_MI_PERSON_010", "entity_id": "PERSON_010", "lang": "mi", "text": "whaea", "pronunciation": {"syllables": ["wha", "e", "a"], "audio_refs": [{"ref": "whaea.mp3", "package": "mi_teaka_v1", "speaker": "Te Aka Māori Dictionary", "dialect": "Standard", "speed": "normal", "quality": "field", "source_url": "https://maoridictionary.co.nz/word/9297", "retrieved": "2026-07-20", "source_license": "Copyright John C Moorfield / Te Aka Māori Dictionary — educational use"}]}},
  SF_AF_PERSON_010: {"id": "SF_AF_PERSON_010", "entity_id": "PERSON_010", "lang": "af", "text": "ma", "pronunciation": {"ipa": "/maː/", "syllables": ["ma"]}},
  SF_EN_PERSON_011: {"id": "SF_EN_PERSON_011", "entity_id": "PERSON_011", "lang": "en", "text": "family", "pronunciation": {"ipa": "/ˈfæməli/", "syllables": ["fam", "e", "ly"], "stress": 1}},
  SF_MI_PERSON_011: {"id": "SF_MI_PERSON_011", "entity_id": "PERSON_011", "lang": "mi", "text": "whānau", "pronunciation": {"syllables": ["whā", "nau"], "audio_refs": [{"ref": "whānau.mp3", "package": "mi_teaka_v1", "speaker": "Te Aka Māori Dictionary", "dialect": "Standard", "speed": "normal", "quality": "field", "source_url": "https://maoridictionary.co.nz/word/10062", "retrieved": "2026-07-20", "source_license": "Copyright John C Moorfield / Te Aka Māori Dictionary — educational use"}]}},
  SF_AF_PERSON_011: {"id": "SF_AF_PERSON_011", "entity_id": "PERSON_011", "lang": "af", "text": "familie", "pronunciation": {"ipa": "/fɑːˈmili/", "syllables": ["fa", "mie", "lie"], "stress": 2}},
  SF_EN_ACTION_010: {"id": "SF_EN_ACTION_010", "entity_id": "ACTION_010", "lang": "en", "text": "give", "pronunciation": {"ipa": "/ɡɪv/", "syllables": ["give"]}},
  SF_MI_ACTION_010: {"id": "SF_MI_ACTION_010", "entity_id": "ACTION_010", "lang": "mi", "text": "hoatu", "pronunciation": {"syllables": ["ho", "a", "tu"], "audio_refs": [{"ref": "hoatu.mp3", "package": "mi_teaka_v1", "speaker": "Te Aka Māori Dictionary", "dialect": "Standard", "speed": "normal", "quality": "field", "source_url": "https://maoridictionary.co.nz/word/1307", "retrieved": "2026-07-20", "source_license": "Copyright John C Moorfield / Te Aka Māori Dictionary — educational use"}]}},
  SF_AF_ACTION_010: {"id": "SF_AF_ACTION_010", "entity_id": "ACTION_010", "lang": "af", "text": "gee", "pronunciation": {"ipa": "/χeː/", "syllables": ["gee"]}},
  SF_EN_ACTION_012: {"id": "SF_EN_ACTION_012", "entity_id": "ACTION_012", "lang": "en", "text": "fill", "pronunciation": {"ipa": "/fɪl/", "syllables": ["fill"]}},
  SF_MI_ACTION_012: {"id": "SF_MI_ACTION_012", "entity_id": "ACTION_012", "lang": "mi", "text": "whakaki", "pronunciation": {"syllables": ["wha", "ka", "ki"], "audio_refs": [{"ref": "whakaki.mp3", "package": "mi_teaka_v1", "speaker": "Te Aka Māori Dictionary", "dialect": "Standard", "speed": "normal", "quality": "field", "source_url": "https://maoridictionary.co.nz/word/9519", "retrieved": "2026-07-20", "source_license": "Copyright John C Moorfield / Te Aka Māori Dictionary — educational use"}]}},
  SF_AF_ACTION_012: {"id": "SF_AF_ACTION_012", "entity_id": "ACTION_012", "lang": "af", "text": "vul", "pronunciation": {"ipa": "/fœl/", "syllables": ["vul"]}},
  SF_EN_STATE_010: {"id": "SF_EN_STATE_010", "entity_id": "STATE_010", "lang": "en", "text": "happy", "pronunciation": {"ipa": "/ˈhæpi/", "syllables": ["hap", "py"], "stress": 1}},
  SF_MI_STATE_010: {"id": "SF_MI_STATE_010", "entity_id": "STATE_010", "lang": "mi", "text": "koa", "pronunciation": {"syllables": ["ko", "a"], "audio_refs": [{"ref": "koa.mp3", "package": "mi_teaka_v1", "speaker": "Te Aka Māori Dictionary", "dialect": "Standard", "speed": "normal", "quality": "field", "source_url": "https://maoridictionary.co.nz/word/2744", "retrieved": "2026-07-20", "source_license": "Copyright John C Moorfield / Te Aka Māori Dictionary — educational use"}]}},
  SF_AF_STATE_010: {"id": "SF_AF_STATE_010", "entity_id": "STATE_010", "lang": "af", "text": "bly", "pronunciation": {"ipa": "/blɛi/", "syllables": ["bly"]}},
  SF_EN_THING_101: {"id": "SF_EN_THING_101", "entity_id": "THING_101", "lang": "en", "text": "dog", "pronunciation": {"ipa": "/dɒɡ/", "syllables": ["dog"]}},
  SF_MI_THING_101: {"id": "SF_MI_THING_101", "entity_id": "THING_101", "lang": "mi", "text": "kurī", "pronunciation": {"syllables": ["ku", "rī"], "audio_refs": [{"ref": "kurī.mp3", "package": "mi_teaka_v1", "speaker": "Te Aka Māori Dictionary", "dialect": "Standard", "speed": "normal", "quality": "field", "source_url": "https://maoridictionary.co.nz/word/3309", "retrieved": "2026-07-20", "source_license": "Copyright John C Moorfield / Te Aka Māori Dictionary — educational use"}]}},
  SF_AF_THING_101: {"id": "SF_AF_THING_101", "entity_id": "THING_101", "lang": "af", "text": "hond", "pronunciation": {"ipa": "/ɦɔnt/", "syllables": ["hond"]}},
  SF_EN_THING_106: {"id": "SF_EN_THING_106", "entity_id": "THING_106", "lang": "en", "text": "rain", "pronunciation": {"ipa": "/reɪn/", "syllables": ["rain"]}},
  SF_MI_THING_106: {"id": "SF_MI_THING_106", "entity_id": "THING_106", "lang": "mi", "text": "ua", "pronunciation": {"syllables": ["u", "a"], "audio_refs": [{"ref": "ua.mp3", "package": "mi_teaka_v1", "speaker": "Te Aka Māori Dictionary", "dialect": "Standard", "speed": "normal", "quality": "field", "source_url": "https://maoridictionary.co.nz/word/51889", "retrieved": "2026-07-20", "source_license": "Copyright John C Moorfield / Te Aka Māori Dictionary — educational use"}]}},
  SF_AF_THING_106: {"id": "SF_AF_THING_106", "entity_id": "THING_106", "lang": "af", "text": "reën", "pronunciation": {"ipa": "/reːən/", "syllables": ["re", "en"]}},
  SF_EN_ACTION_013: {"id": "SF_EN_ACTION_013", "entity_id": "ACTION_013", "lang": "en", "text": "fall", "pronunciation": {"ipa": "/fɔːl/", "syllables": ["fall"]}},
  SF_MI_ACTION_013: {"id": "SF_MI_ACTION_013", "entity_id": "ACTION_013", "lang": "mi", "text": "heke", "pronunciation": {"syllables": ["he", "ke"], "audio_refs": [{"ref": "heke.mp3", "package": "mi_teaka_v1", "speaker": "Te Aka Māori Dictionary", "dialect": "Standard", "speed": "normal", "quality": "field", "source_url": "https://maoridictionary.co.nz/word/1038", "retrieved": "2026-07-20", "source_license": "Copyright John C Moorfield / Te Aka Māori Dictionary — educational use"}]}},
  SF_AF_ACTION_013: {"id": "SF_AF_ACTION_013", "entity_id": "ACTION_013", "lang": "af", "text": "val", "pronunciation": {"ipa": "/fal/", "syllables": ["val"]}},
  SF_EN_ACTION_014: {"id": "SF_EN_ACTION_014", "entity_id": "ACTION_014", "lang": "en", "text": "flow", "pronunciation": {"ipa": "/floʊ/", "syllables": ["flow"]}},
  SF_MI_ACTION_014: {"id": "SF_MI_ACTION_014", "entity_id": "ACTION_014", "lang": "mi", "text": "rere", "pronunciation": {"syllables": ["re", "re"], "audio_refs": [{"ref": "rere.mp3", "package": "mi_teaka_v1", "speaker": "Te Aka Māori Dictionary", "dialect": "Standard", "speed": "normal", "quality": "field", "source_url": "https://maoridictionary.co.nz/word/6719", "retrieved": "2026-07-20", "source_license": "Copyright John C Moorfield / Te Aka Māori Dictionary — educational use"}]}},
  SF_AF_ACTION_014: {"id": "SF_AF_ACTION_014", "entity_id": "ACTION_014", "lang": "af", "text": "vloei", "pronunciation": {"ipa": "/flui/", "syllables": ["vloei"]}},
  SF_EN_THING_100: {"id": "SF_EN_THING_100", "entity_id": "THING_100", "lang": "en", "text": "tree", "pronunciation": {"ipa": "/triː/", "syllables": ["tree"]}},
  SF_MI_THING_100: {"id": "SF_MI_THING_100", "entity_id": "THING_100", "lang": "mi", "text": "rākau", "pronunciation": {"syllables": ["rā", "kau"], "audio_refs": [{"ref": "rākau.mp3", "package": "mi_teaka_v1", "speaker": "Te Aka Māori Dictionary", "dialect": "Standard", "speed": "normal", "quality": "field", "source_url": "https://maoridictionary.co.nz/word/6439", "retrieved": "2026-07-20", "source_license": "Copyright John C Moorfield / Te Aka Māori Dictionary — educational use"}]}},
  SF_AF_THING_100: {"id": "SF_AF_THING_100", "entity_id": "THING_100", "lang": "af", "text": "boom", "pronunciation": {"ipa": "/bʊəːm/", "syllables": ["boom"]}},
  SF_EN_ACTION_015: {"id": "SF_EN_ACTION_015", "entity_id": "ACTION_015", "lang": "en", "text": "grow", "pronunciation": {"ipa": "/ɡroʊ/", "syllables": ["grow"]}},
  SF_MI_ACTION_015: {"id": "SF_MI_ACTION_015", "entity_id": "ACTION_015", "lang": "mi", "text": "tipu", "pronunciation": {"syllables": ["ti", "pu"], "audio_refs": [{"ref": "tipu.mp3", "package": "mi_teaka_v1", "speaker": "Te Aka Māori Dictionary", "dialect": "Standard", "speed": "normal", "quality": "field", "source_url": "https://maoridictionary.co.nz/word/8168", "retrieved": "2026-07-20", "source_license": "Copyright John C Moorfield / Te Aka Māori Dictionary — educational use"}]}},
  SF_AF_ACTION_015: {"id": "SF_AF_ACTION_015", "entity_id": "ACTION_015", "lang": "af", "text": "groei", "pronunciation": {"ipa": "/χrui/", "syllables": ["groei"]}},
  SF_EN_THING_102: {"id": "SF_EN_THING_102", "entity_id": "THING_102", "lang": "en", "text": "fish", "pronunciation": {"ipa": "/fɪʃ/", "syllables": ["fish"]}},
  SF_MI_THING_102: {"id": "SF_MI_THING_102", "entity_id": "THING_102", "lang": "mi", "text": "ika", "pronunciation": {"syllables": ["i", "ka"], "audio_refs": [{"ref": "ika.mp3", "package": "mi_teaka_v1", "speaker": "Te Aka Māori Dictionary", "dialect": "Standard", "speed": "normal", "quality": "field", "source_url": "https://maoridictionary.co.nz/word/42348", "retrieved": "2026-07-20", "source_license": "Copyright John C Moorfield / Te Aka Māori Dictionary — educational use"}]}},
  SF_AF_THING_102: {"id": "SF_AF_THING_102", "entity_id": "THING_102", "lang": "af", "text": "vis", "pronunciation": {"ipa": "/fəs/", "syllables": ["vis"]}},
  SF_EN_ACTION_016: {"id": "SF_EN_ACTION_016", "entity_id": "ACTION_016", "lang": "en", "text": "live", "pronunciation": {"ipa": "/lɪv/", "syllables": ["live"]}},
  SF_MI_ACTION_016: {"id": "SF_MI_ACTION_016", "entity_id": "ACTION_016", "lang": "mi", "text": "noho", "pronunciation": {"syllables": ["no", "ho"], "audio_refs": [{"ref": "noho.mp3", "package": "mi_teaka_v1", "speaker": "Te Aka Māori Dictionary", "dialect": "Standard", "speed": "normal", "quality": "field", "source_url": "https://maoridictionary.co.nz/word/53247", "retrieved": "2026-07-20", "source_license": "Copyright John C Moorfield / Te Aka Māori Dictionary — educational use"}]}},
  SF_AF_ACTION_016: {"id": "SF_AF_ACTION_016", "entity_id": "ACTION_016", "lang": "af", "text": "woon", "pronunciation": {"ipa": "/vʊəːn/", "syllables": ["woon"]}},
  SF_EN_ACTION_017: {"id": "SF_EN_ACTION_017", "entity_id": "ACTION_017", "lang": "en", "text": "swim", "pronunciation": {"ipa": "/swɪm/", "syllables": ["swim"]}},
  SF_MI_ACTION_017: {"id": "SF_MI_ACTION_017", "entity_id": "ACTION_017", "lang": "mi", "text": "kauhoe", "pronunciation": {"syllables": ["kau", "ho", "e"], "audio_refs": [{"ref": "kauhoe.mp3", "package": "mi_teaka_v1", "speaker": "Te Aka Māori Dictionary", "dialect": "Standard", "speed": "normal", "quality": "field", "source_url": "https://maoridictionary.co.nz/word/2424", "retrieved": "2026-07-20", "source_license": "Copyright John C Moorfield / Te Aka Māori Dictionary — educational use"}]}},
  SF_AF_ACTION_017: {"id": "SF_AF_ACTION_017", "entity_id": "ACTION_017", "lang": "af", "text": "swem", "pronunciation": {"ipa": "/svɛm/", "syllables": ["swem"]}},
  SF_EN_THING_107: {"id": "SF_EN_THING_107", "entity_id": "THING_107", "lang": "en", "text": "net", "pronunciation": {"ipa": "/nɛt/", "syllables": ["net"]}},
  SF_MI_THING_107: {"id": "SF_MI_THING_107", "entity_id": "THING_107", "lang": "mi", "text": "kupenga", "pronunciation": {"syllables": ["ku", "pe", "nga"], "audio_refs": [{"ref": "kupenga.mp3", "package": "mi_teaka_v1", "speaker": "Te Aka Māori Dictionary", "dialect": "Standard", "speed": "normal", "quality": "field", "source_url": "https://maoridictionary.co.nz/word/3274", "retrieved": "2026-07-20", "source_license": "Copyright John C Moorfield / Te Aka Māori Dictionary — educational use"}]}},
  SF_AF_THING_107: {"id": "SF_AF_THING_107", "entity_id": "THING_107", "lang": "af", "text": "net", "pronunciation": {"ipa": "/nɛt/", "syllables": ["net"]}},
  SF_EN_ACTION_018: {"id": "SF_EN_ACTION_018", "entity_id": "ACTION_018", "lang": "en", "text": "catch", "pronunciation": {"ipa": "/kætʃ/", "syllables": ["catch"]}},
  SF_MI_ACTION_018: {"id": "SF_MI_ACTION_018", "entity_id": "ACTION_018", "lang": "mi", "text": "hopu", "pronunciation": {"syllables": ["ho", "pu"], "audio_refs": [{"ref": "hopu.mp3", "package": "mi_teaka_v1", "speaker": "Te Aka Māori Dictionary", "dialect": "Standard", "speed": "normal", "quality": "field", "source_url": "https://maoridictionary.co.nz/word/1405", "retrieved": "2026-07-20", "source_license": "Copyright John C Moorfield / Te Aka Māori Dictionary — educational use"}]}},
  SF_AF_ACTION_018: {"id": "SF_AF_ACTION_018", "entity_id": "ACTION_018", "lang": "af", "text": "vang", "pronunciation": {"ipa": "/faŋ/", "syllables": ["vang"]}},
  SF_EN_THING_103: {"id": "SF_EN_THING_103", "entity_id": "THING_103", "lang": "en", "text": "cup", "pronunciation": {"ipa": "/kʌp/", "syllables": ["cup"]}},
  SF_MI_THING_103: {"id": "SF_MI_THING_103", "entity_id": "THING_103", "lang": "mi", "text": "kapu", "pronunciation": {"syllables": ["ka", "pu"], "audio_refs": [{"ref": "kapu.mp3", "package": "mi_teaka_v1", "speaker": "Te Aka Māori Dictionary", "dialect": "Standard", "speed": "normal", "quality": "field", "source_url": "https://maoridictionary.co.nz/word/2248", "retrieved": "2026-07-20", "source_license": "Copyright John C Moorfield / Te Aka Māori Dictionary — educational use"}]}},
  SF_AF_THING_103: {"id": "SF_AF_THING_103", "entity_id": "THING_103", "lang": "af", "text": "koppie", "pronunciation": {"ipa": "/ˈkɔpi/", "syllables": ["kop", "pie"], "stress": 1}},
  SF_EN_THING_104: {"id": "SF_EN_THING_104", "entity_id": "THING_104", "lang": "en", "text": "fire", "pronunciation": {"ipa": "/ˈfaɪər/", "syllables": ["fy", "er"], "stress": 1}},
  SF_MI_THING_104: {"id": "SF_MI_THING_104", "entity_id": "THING_104", "lang": "mi", "text": "ahi", "pronunciation": {"syllables": ["a", "hi"], "audio_refs": [{"ref": "ahi.mp3", "package": "mi_teaka_v1", "speaker": "Te Aka Māori Dictionary", "dialect": "Standard", "speed": "normal", "quality": "field", "source_url": "https://maoridictionary.co.nz/word/69", "retrieved": "2026-07-20", "source_license": "Copyright John C Moorfield / Te Aka Māori Dictionary — educational use"}]}},
  SF_AF_THING_104: {"id": "SF_AF_THING_104", "entity_id": "THING_104", "lang": "af", "text": "vuur", "pronunciation": {"ipa": "/fyr/", "syllables": ["vuur"]}},
  SF_EN_THING_105: {"id": "SF_EN_THING_105", "entity_id": "THING_105", "lang": "en", "text": "food", "pronunciation": {"ipa": "/fuːd/", "syllables": ["food"]}},
  SF_MI_THING_105: {"id": "SF_MI_THING_105", "entity_id": "THING_105", "lang": "mi", "text": "kai", "pronunciation": {"syllables": ["kai"], "audio_refs": [{"ref": "kai.mp3", "package": "mi_teaka_v1", "speaker": "Te Aka Māori Dictionary", "dialect": "Standard", "speed": "normal", "quality": "field", "source_url": "https://maoridictionary.co.nz/word/1894", "retrieved": "2026-07-20", "source_license": "Copyright John C Moorfield / Te Aka Māori Dictionary — educational use"}]}},
  SF_AF_THING_105: {"id": "SF_AF_THING_105", "entity_id": "THING_105", "lang": "af", "text": "kos", "pronunciation": {"ipa": "/kɔs/", "syllables": ["kos"]}},
  SF_EN_ACTION_019: {"id": "SF_EN_ACTION_019", "entity_id": "ACTION_019", "lang": "en", "text": "cook", "pronunciation": {"ipa": "/kʊk/", "syllables": ["cook"]}},
  SF_MI_ACTION_019: {"id": "SF_MI_ACTION_019", "entity_id": "ACTION_019", "lang": "mi", "text": "tunu", "pronunciation": {"syllables": ["tu", "nu"], "audio_refs": [{"ref": "tunu.mp3", "package": "mi_teaka_v1", "speaker": "Te Aka Māori Dictionary", "dialect": "Standard", "speed": "normal", "quality": "field", "source_url": "https://maoridictionary.co.nz/word/8712", "retrieved": "2026-07-20", "source_license": "Copyright John C Moorfield / Te Aka Māori Dictionary — educational use"}]}},
  SF_AF_ACTION_019: {"id": "SF_AF_ACTION_019", "entity_id": "ACTION_019", "lang": "af", "text": "kook", "pronunciation": {"ipa": "/kʊəːk/", "syllables": ["kook"]}},
  SF_EN_ACTION_020: {"id": "SF_EN_ACTION_020", "entity_id": "ACTION_020", "lang": "en", "text": "share", "pronunciation": {"ipa": "/ʃɛr/", "syllables": ["share"]}},
  SF_MI_ACTION_020: {"id": "SF_MI_ACTION_020", "entity_id": "ACTION_020", "lang": "mi", "text": "tohatoha", "pronunciation": {"syllables": ["to", "ha", "to", "ha"], "audio_refs": [{"ref": "tohatoha.mp3", "package": "mi_teaka_v1", "speaker": "Te Aka Māori Dictionary", "dialect": "Standard", "speed": "normal", "quality": "field", "source_url": "https://maoridictionary.co.nz/word/8293", "retrieved": "2026-07-20", "source_license": "Copyright John C Moorfield / Te Aka Māori Dictionary — educational use"}]}},
  SF_AF_ACTION_020: {"id": "SF_AF_ACTION_020", "entity_id": "ACTION_020", "lang": "af", "text": "deel", "pronunciation": {"ipa": "/deːl/", "syllables": ["deel"]}},
  SF_EN_ACTION_021: {"id": "SF_EN_ACTION_021", "entity_id": "ACTION_021", "lang": "en", "text": "eat", "pronunciation": {"ipa": "/iːt/", "syllables": ["eat"]}},
  SF_MI_ACTION_021: {"id": "SF_MI_ACTION_021", "entity_id": "ACTION_021", "lang": "mi", "text": "kai", "pronunciation": {"syllables": ["kai"], "audio_refs": [{"ref": "kai.mp3", "package": "mi_teaka_v1", "speaker": "Te Aka Māori Dictionary", "dialect": "Standard", "speed": "normal", "quality": "field", "source_url": "https://maoridictionary.co.nz/word/1894", "retrieved": "2026-07-20", "source_license": "Copyright John C Moorfield / Te Aka Māori Dictionary — educational use"}]}},
  SF_AF_ACTION_021: {"id": "SF_AF_ACTION_021", "entity_id": "ACTION_021", "lang": "af", "text": "eet", "pronunciation": {"ipa": "/eːt/", "syllables": ["eet"]}},
  SF_EN_STATE_011: {"id": "SF_EN_STATE_011", "entity_id": "STATE_011", "lang": "en", "text": "full", "pronunciation": {"ipa": "/fʊl/", "syllables": ["full"]}},
  SF_MI_STATE_011: {"id": "SF_MI_STATE_011", "entity_id": "STATE_011", "lang": "mi", "text": "mākona", "pronunciation": {"syllables": ["mā", "ko", "na"], "audio_refs": [{"ref": "mākona.mp3", "package": "mi_teaka_v1", "speaker": "Te Aka Māori Dictionary", "dialect": "Standard", "speed": "normal", "quality": "field", "source_url": "https://maoridictionary.co.nz/word/3553", "retrieved": "2026-07-20", "source_license": "Copyright John C Moorfield / Te Aka Māori Dictionary — educational use"}]}},
  SF_AF_STATE_011: {"id": "SF_AF_STATE_011", "entity_id": "STATE_011", "lang": "af", "text": "versadig", "pronunciation": {"ipa": "/fərˈsɑːdəx/", "syllables": ["ver", "sa", "dig"], "stress": 2}},
  SF_EN_ACTION_022: {"id": "SF_EN_ACTION_022", "entity_id": "ACTION_022", "lang": "en", "text": "thank", "pronunciation": {"ipa": "/θæŋk/", "syllables": ["thank"]}},
  SF_MI_ACTION_022: {"id": "SF_MI_ACTION_022", "entity_id": "ACTION_022", "lang": "mi", "text": "whakawhetai", "pronunciation": {"syllables": ["wha", "ka", "whe", "tai"], "audio_refs": [{"ref": "whakawhetai.mp3", "package": "mi_teaka_v1", "speaker": "Te Aka Māori Dictionary", "dialect": "Standard", "speed": "normal", "quality": "field", "source_url": "https://maoridictionary.co.nz/word/10035", "retrieved": "2026-07-20", "source_license": "Copyright John C Moorfield / Te Aka Māori Dictionary — educational use"}]}},
  SF_AF_ACTION_022: {"id": "SF_AF_ACTION_022", "entity_id": "ACTION_022", "lang": "af", "text": "bedank", "pronunciation": {"ipa": "/bəˈdaŋk/", "syllables": ["be", "dank"], "stress": 2}},
  SF_EN_STATE_012: {"id": "SF_EN_STATE_012", "entity_id": "STATE_012", "lang": "en", "text": "grateful", "pronunciation": {"ipa": "/ˈɡreɪtfəl/", "syllables": ["grate", "ful"], "stress": 1}},
  SF_MI_STATE_012: {"id": "SF_MI_STATE_012", "entity_id": "STATE_012", "lang": "mi", "text": "whakawhetai", "pronunciation": {"syllables": ["wha", "ka", "whe", "tai"], "audio_refs": [{"ref": "whakawhetai.mp3", "package": "mi_teaka_v1", "speaker": "Te Aka Māori Dictionary", "dialect": "Standard", "speed": "normal", "quality": "field", "source_url": "https://maoridictionary.co.nz/word/10035", "retrieved": "2026-07-20", "source_license": "Copyright John C Moorfield / Te Aka Māori Dictionary — educational use"}]}},
  SF_AF_STATE_012: {"id": "SF_AF_STATE_012", "entity_id": "STATE_012", "lang": "af", "text": "dankbaar", "pronunciation": {"ipa": "/ˈdaŋkbɑːr/", "syllables": ["dank", "baar"], "stress": 1}},
  SF_EN_STATE_013: {"id": "SF_EN_STATE_013", "entity_id": "STATE_013", "lang": "en", "text": "together", "pronunciation": {"ipa": "/təˈɡɛðər/", "syllables": ["to", "geth", "er"], "stress": 2}},
  SF_MI_STATE_013: {"id": "SF_MI_STATE_013", "entity_id": "STATE_013", "lang": "mi", "text": "noho tahi", "pronunciation": {"syllables": ["no", "ho", "ta", "hi"], "audio_refs": [{"ref": "noho_tahi.mp3", "package": "mi_teaka_v1", "speaker": "Te Aka Māori Dictionary", "dialect": "Standard", "speed": "normal", "quality": "field", "source_url": "https://maoridictionary.co.nz/word/39458", "retrieved": "2026-07-20", "source_license": "Copyright John C Moorfield / Te Aka Māori Dictionary — educational use"}]}},
  SF_AF_STATE_013: {"id": "SF_AF_STATE_013", "entity_id": "STATE_013", "lang": "af", "text": "saam", "pronunciation": {"ipa": "/sɑːm/", "syllables": ["saam"]}},
  SF_AF_PHRASE_001: {"id": "SF_AF_PHRASE_001", "entity_id": "PHRASE_001", "lang": "af", "text": "dankie", "pronunciation": {"ipa": "/ˈdɑːnki/", "syllables": ["dan", "kie"], "stress": 1}},
};
var SURFACE_FORM_INDEX = {
  "THING_001": {
    "en": "SF_EN_THING_001",
    "mi": "SF_MI_THING_001",
    "af": "SF_AF_THING_001",
  },
  "PLACE_005": {
    "en": "SF_EN_PLACE_005",
    "mi": "SF_MI_PLACE_005",
    "af": "SF_AF_PLACE_005",
  },
  "STATE_001": {
    "en": "SF_EN_STATE_001",
    "mi": "SF_MI_STATE_001",
    "af": "SF_AF_STATE_001",
  },
  "STATE_002": {
    "en": "SF_EN_STATE_002",
    "mi": "SF_MI_STATE_002",
    "af": "SF_AF_STATE_002",
  },
  "ACTION_001": {
    "en": "SF_EN_ACTION_001",
    "mi": "SF_MI_ACTION_001",
    "af": "SF_AF_ACTION_001",
  },
  "ACTION_002": {
    "en": "SF_EN_ACTION_002",
    "mi": "SF_MI_ACTION_002",
    "af": "SF_AF_ACTION_002",
  },
  "PERSON_003": {
    "en": "SF_EN_PERSON_003",
    "mi": "SF_MI_PERSON_003",
    "af": "SF_AF_PERSON_003",
  },
  "PERSON_010": {
    "en": "SF_EN_PERSON_010",
    "mi": "SF_MI_PERSON_010",
    "af": "SF_AF_PERSON_010",
  },
  "PERSON_011": {
    "en": "SF_EN_PERSON_011",
    "mi": "SF_MI_PERSON_011",
    "af": "SF_AF_PERSON_011",
  },
  "ACTION_010": {
    "en": "SF_EN_ACTION_010",
    "mi": "SF_MI_ACTION_010",
    "af": "SF_AF_ACTION_010",
  },
  "ACTION_012": {
    "en": "SF_EN_ACTION_012",
    "mi": "SF_MI_ACTION_012",
    "af": "SF_AF_ACTION_012",
  },
  "STATE_010": {
    "en": "SF_EN_STATE_010",
    "mi": "SF_MI_STATE_010",
    "af": "SF_AF_STATE_010",
  },
  "THING_101": {
    "en": "SF_EN_THING_101",
    "mi": "SF_MI_THING_101",
    "af": "SF_AF_THING_101",
  },
  "THING_106": {
    "en": "SF_EN_THING_106",
    "mi": "SF_MI_THING_106",
    "af": "SF_AF_THING_106",
  },
  "ACTION_013": {
    "en": "SF_EN_ACTION_013",
    "mi": "SF_MI_ACTION_013",
    "af": "SF_AF_ACTION_013",
  },
  "ACTION_014": {
    "en": "SF_EN_ACTION_014",
    "mi": "SF_MI_ACTION_014",
    "af": "SF_AF_ACTION_014",
  },
  "THING_100": {
    "en": "SF_EN_THING_100",
    "mi": "SF_MI_THING_100",
    "af": "SF_AF_THING_100",
  },
  "ACTION_015": {
    "en": "SF_EN_ACTION_015",
    "mi": "SF_MI_ACTION_015",
    "af": "SF_AF_ACTION_015",
  },
  "THING_102": {
    "en": "SF_EN_THING_102",
    "mi": "SF_MI_THING_102",
    "af": "SF_AF_THING_102",
  },
  "ACTION_016": {
    "en": "SF_EN_ACTION_016",
    "mi": "SF_MI_ACTION_016",
    "af": "SF_AF_ACTION_016",
  },
  "ACTION_017": {
    "en": "SF_EN_ACTION_017",
    "mi": "SF_MI_ACTION_017",
    "af": "SF_AF_ACTION_017",
  },
  "THING_107": {
    "en": "SF_EN_THING_107",
    "mi": "SF_MI_THING_107",
    "af": "SF_AF_THING_107",
  },
  "ACTION_018": {
    "en": "SF_EN_ACTION_018",
    "mi": "SF_MI_ACTION_018",
    "af": "SF_AF_ACTION_018",
  },
  "THING_103": {
    "en": "SF_EN_THING_103",
    "mi": "SF_MI_THING_103",
    "af": "SF_AF_THING_103",
  },
  "THING_104": {
    "en": "SF_EN_THING_104",
    "mi": "SF_MI_THING_104",
    "af": "SF_AF_THING_104",
  },
  "THING_105": {
    "en": "SF_EN_THING_105",
    "mi": "SF_MI_THING_105",
    "af": "SF_AF_THING_105",
  },
  "ACTION_019": {
    "en": "SF_EN_ACTION_019",
    "mi": "SF_MI_ACTION_019",
    "af": "SF_AF_ACTION_019",
  },
  "ACTION_020": {
    "en": "SF_EN_ACTION_020",
    "mi": "SF_MI_ACTION_020",
    "af": "SF_AF_ACTION_020",
  },
  "ACTION_021": {
    "en": "SF_EN_ACTION_021",
    "mi": "SF_MI_ACTION_021",
    "af": "SF_AF_ACTION_021",
  },
  "STATE_011": {
    "en": "SF_EN_STATE_011",
    "mi": "SF_MI_STATE_011",
    "af": "SF_AF_STATE_011",
  },
  "ACTION_022": {
    "en": "SF_EN_ACTION_022",
    "mi": "SF_MI_ACTION_022",
    "af": "SF_AF_ACTION_022",
  },
  "STATE_012": {
    "en": "SF_EN_STATE_012",
    "mi": "SF_MI_STATE_012",
    "af": "SF_AF_STATE_012",
  },
  "STATE_013": {
    "en": "SF_EN_STATE_013",
    "mi": "SF_MI_STATE_013",
    "af": "SF_AF_STATE_013",
  },
};