var VOICE_PACKAGES = {
  "af_placeholder_v1": {"id": "af_placeholder_v1", "name": "af (Standard)", "language": "af", "dialect": "Standard", "register": "educational", "license": "CC-BY-SA-4.0", "version": "1.0", "base_path": "voices/af_placeholder_v1/audio/", "format": "ogg", "sample_rate": 48000, "speaker": {"name": "TTS Fallback", "native": false}, "coverage": {"corpus": "river_world_alpha", "experience_count": 10, "surface_form_count": 33, "percentage": 0}, "review": {"native": false, "reviewed": false, "pronunciation": "unreviewed", "grammar": "unreviewed"}},
  "af_v1": {"id": "af_v1", "name": "Hannes Afrikaans", "language": "af", "dialect": "South African", "register": "conversational", "license": "CC-BY-4.0", "version": "1.0", "base_path": "voices/af_v1/audio/", "format": "webm", "sample_rate": 48000, "speaker": {"name": "Hannes", "native": true}, "coverage": {"corpus": "visit_aotearoa_alpha", "experience_count": 0, "surface_form_count": 1, "phrase_count": 41, "percentage": 5}, "review": {"native": true, "reviewed": false, "pronunciation": "pending", "grammar": "unreviewed"}, "recorded": "2026-07-21"},
  "en_placeholder_v1": {"id": "en_placeholder_v1", "name": "en (Standard)", "language": "en", "dialect": "Standard", "register": "educational", "license": "CC-BY-SA-4.0", "version": "1.0", "base_path": "voices/en_placeholder_v1/audio/", "format": "ogg", "sample_rate": 48000, "speaker": {"name": "TTS Fallback", "native": false}, "coverage": {"corpus": "river_world_alpha", "experience_count": 10, "surface_form_count": 33, "percentage": 0}, "review": {"native": false, "reviewed": false, "pronunciation": "unreviewed", "grammar": "unreviewed"}},
  "mi_teaka_v1": {"id": "mi_teaka_v1", "name": "Te Aka Māori Dictionary", "language": "mi", "dialect": "Standard", "register": "educational", "license": "CC-BY-SA-4.0, audio from Te Aka Māori Dictionary (educational use)", "version": "2.0", "base_path": "voices/mi_teaka_v1/audio/", "format": "mp3", "sample_rate": 48000, "speaker": {"name": "Te Aka Māori Dictionary", "native": true}, "coverage": {"corpus": "visit_aotearoa_alpha", "experience_count": 12, "surface_form_count": 89, "percentage": 100}, "review": {"native": true, "reviewed": true, "pronunciation": "verified", "grammar": "unreviewed"}, "recorded": "2024-01-01", "updated": "2026-07-21"},
};
var DEFAULT_VOICE_PACKAGES = {
  "af": "af_v1",
  "en": "en_placeholder_v1",
  "mi": "mi_teaka_v1",
};